[package]
name = "metadata-minter"
authors = [
  "Kromsten <kromsten@megarock.app>"
]
description = "Stargaze on-chaon metadata minter contract based on merkle trees"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema         = { workspace = true }
cosmwasm-std            = { workspace = true }
cw2                     = { workspace = true }
cw721                   = { workspace = true }
cw721-base              = { workspace = true, features = ["library"] }
cw-storage-plus         = { workspace = true }
cw-utils                = { workspace = true }
schemars                = { workspace = true }
serde                   = { workspace = true }
sha2                    = { workspace = true }
sg1                     = { workspace = true }
sg2                     = { workspace = true }
sg4                     = { workspace = true }
sg721                   = { workspace = true }
sg-std                  = { workspace = true }
sg-whitelist            = { workspace = true, features = ["library"] }
whitelist-mtree         = { workspace = true, features = ["library"] }
thiserror               = { workspace = true }
url                     = { workspace = true }
hex                     = { workspace = true }
semver                  = { workspace = true }
sg-metadata             = { workspace = true }
rs_merkle               = { version = "1.4.2", default-features = false }

metadata-factory        = { workspace = true, features = ["library"] }
sg721-metadata-onchain  = { workspace = true, features = ["library"] }